version: '3'

services:
  mongodb:
    image: 'mongo'
    container_name: 'mongodb-cont'
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=infra
      - MONGO_INITDB_ROOT_PASSWORD=infra
    ports:
      - '27017:27017'