server:
  port: 8083

spring:
  application:
    name: approval
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      indent_output: true
  data:
    mongodb:
      uri: mongodb://10.3.3.3:27017/developer-exercise-db?connectTimeoutMS=120000&socketTimeoutMS=120000
      auto-index-creation: true